Add Advances in notification
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #117
Opened 2024-11-10 11:49 UTC by JereC4str0

## Avance de notificaciones usando NTFY

## Enviando notificacion con curl:
[![imagen.png](https://i.postimg.cc/CxKKz2WR/imagen.png)](https://postimg.cc/7fp4RKP4)
## Recibiendo desde aplicacion: 
[![imagen.png](https://i.postimg.cc/NfdHJRtr/imagen.png)](https://postimg.cc/TpW1hLpR)

Despues de haber recibido la aplicacion intente automatizar el proceso de enviar las notificaciones: 

https://github.com/user-attachments/assets/5995e176-5284-45c5-b4d5-99f477f5a3f2

Esto es un intento de entender como es que funciona NTFY, no se debe tomar como algo definitivo, si piensan que puede tener futuro podemos mejorarlo un poco más

2024-11-11 16:04 UTC, javierbrk commented
lo ideal en este caso es tener la posiblidad de no tener que usar otra funcion si no que los errores sean alertas en grafana, en telegram, en ntfy 
entonces solo agregar que en donde se envia a grafana en la funcion de log, si esta habilitado notyfy y si tiene el hash de la etiqueta que lo envie .
De esa manera no es necesario que escribamos mensajes por todo el código.

2024-11-11 16:54 UTC, JereC4str0 commented
excelente, entonces meto la misma lógica que envia los mensajes a ntfy en la función que envia los logs a grafana?

2024-11-11 16:55 UTC, JereC4str0 commented
a que te referís con "si está habilitado ntfy"?

2024-11-11 18:21 UTC, javierbrk commented
en el archivo de logs.lua tenemos la posiblidad de enviar a grafana si esa funcioanlidad esta habilitada. 
pone un flag que habilite o deshbilite el envio de notificaciones 
que cada vez que se cambie el valor del hash le cambie a log el valor de la url del notifi
que cada vez que se cargue la configuracion desde el json le cargue el valor al log

2024-11-12 20:44 UTC, JereC4str0 commented
tengo entendido que el hash seria el topico de ntfy, este es fijo o por lo menos desde la aplicacion, hablas de actualizar el hash(que contiene el mac por defecto) por el topico de ntfy?

2024-11-12 20:46 UTC, JereC4str0 commented
hay una flag que deshabilita el envio de mensajes a grafana en esta [linea](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/blob/0c1dba12f7130e35028b175c824a1ebceb88ce6e/src/embedded/libs/log.lua#L15)

2024-12-04 19:12 UTC, javierbrk requested changes
re hacer esta pull sin cambios innecesarios, evitar en lo posible los cambios de tabulacion

2024-12-20 09:47 UTC, closed without merging