INICIALES is incubator.incubator_name now
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #121
Opened 2024-11-14 03:18 UTC by JereC4str0

Esta pull request busca resolver el issue numero #119

2024-12-04 18:54 UTC, javierbrk commented
el ssid del wifi de la incubadora debería ser también el nombre de la incubadora 
W.ap_config.ssid = "incubator"

2024-12-06 12:33 UTC, JereC4str0 commented
> el ssid del wifi de la incubadora debería ser también el nombre de la incubadora W.ap_config.ssid = "incubator"

lo meto en esta misma pull request?

2024-12-07 07:55 UTC, javierbrk commented
Vi que estaba separado después vamos por esa alternativa



On Fri, Dec 6, 2024, 09:33 Jere Castro ***@***.***> wrote:

> el ssid del wifi de la incubadora debería ser también el nombre de la
> incubadora W.ap_config.ssid = "incubator"
>
> lo meto en esta misma pull request?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/pull/121#issuecomment-2523122065>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABE2I2FMCEGW5LURV3PILZL2EGKTPAVCNFSM6AAAAABRX46URGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMRTGEZDEMBWGU>
> .
> You are receiving this because your review was requested.Message ID:
> <AlterMundi-MonitoreoyControl/Proyecto-Incubadora/pull/121/c2523122065@
> github.com>
>

2024-12-16 14:31 UTC, javierbrk requested changes
ponerlo en la 419 de incubator 
agregar una nota en credentials para que sepamos que esa variable se va a sobre escribir

2024-12-16 14:31 UTC, javierbrk commented on src/embedded/app/SendToGrafana.lua
> +local incubator = require("incubator")
esto deberia salir de aqui

2024-12-16 14:31 UTC, javierbrk commented on src/embedded/app/wifiinit.lua
> +	INICIALES = incubator.incubator_name
no va aca

2024-12-16 14:45 UTC, closed without merging