Fix incubator_name
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #129
Opened 2024-11-21 10:16 UTC by JereC4str0

# Incubator Name
Esta PR busca solucionar el commit numero: #113 

## Cambios
- Agregué dos segundos de delay a cada peticion web que hacen las pruebas, se estaban enviando casi al mismo tiempo, eso no le daba tiempo al ESP para poder procesar los cambios
- Cambíe el valor que debe tener "incubator_name" para que sea posible el nombre con la MAC
- Modifiqué las pruebas TDD
- La IP por defecto del ESP que tenia un modulo de las pruebas unitarias estaba mal, tambien corregí eso

### Adjunto salida de las distintas pruebas manuales y automatizadas:

#### Pruebas en la aplicacion:
[![imagen.png](https://i.postimg.cc/qB39CQ60/imagen.png)](https://postimg.cc/jCR8pHhk)
[![imagen.png](https://i.postimg.cc/X76tKF95/imagen.png)](https://postimg.cc/QVS6hF4N)
####  TDD
[![imagen.png](https://i.postimg.cc/hP862j05/imagen.png)](https://postimg.cc/JGnpnRvN)

2024-11-21 11:55 UTC, javierbrk requested changes
esta pull tiene muchos cambios no relacionados al issue. 
des hacer los cambios no relacionados al issue del nombre. 

si existe otro problema abrir otra issue. Hacer otra pull request

2024-11-21 11:55 UTC, javierbrk commented on src/embedded/app/configurator.lua
> -      status.min_temp = incubator.set_min_temp(tonumber(value))
porque sacar el tonumber ?

2024-11-21 11:55 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/tables.lua
> +	incubator_name = "404:HuevoNoEncontradoEnIncubadora"  -- nombre muy corto o inválido
muy corto es una prueba ... y cual es el problema con que el nombre de la incubadora sea un caracter ? incubadora "a" ... creo que no es problema ... deberia aceptar un solo caracter. No vacío. No null. Pero si corto ... 

Tampoco veo una prueba donde tomes el nombre con la mac como vendría desde una incu sin inicializar

2024-11-21 11:55 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if new_max_temp ~= nil and new_max_temp >= 0
porque este cambio ? podes poner comentarios sobre estas decisiones en el código. 
no es correcto hacer una pull con 20 cambios que no están del todo relacionados con el título de la pull ni con el problema del nombre de la incubadora mencionado en la descripción. 

Por favor, solo resolver el nombre de la incubadora en esta pull.

2024-11-21 11:55 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if new_max_temp ~= nil and new_max_temp >= 0
para eso des hacer todos los cambios no relacionados con este tema en todos los archivos y hacer un nuevo commit que vuelve a dejar todo como estaba. Solo cambios asociados al problema que queremos resolver.

2024-11-21 12:00 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +if type(new_incubator_name) == "string" and #new_incubator_name < 30 then
@AnnieScigliano  estaria bueno que desde la app podamos poner tambien esta restriccion en la caja de texto, que no deje poner mas de 30 caracteres ...

2024-11-26 22:33 UTC, JereC4str0 commented on src/embedded/app/configurator.lua
> -      status.min_temp = incubator.set_min_temp(tonumber(value))
en incubator.lua ya las guardas de estos valores lo validan que sea un numero por ejemplo en esta [linea](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/blob/0a6ea493a8787608c90f48c7050f9465f5df4c4f/src/embedded/app/incubator.lua#L315)

2024-11-26 22:34 UTC, JereC4str0 commented on src/embedded/test/tdd_api_rest/tables.lua
> +	incubator_name = "404:HuevoNoEncontradoEnIncubadora"  -- nombre muy corto o inválido
entendible, lo que valida esta prueba es que la longitud del nombre no sea mayor a 30 caracteres, voy a agregar las pruebas que mencionas en otra PR

2024-11-27 14:34 UTC, javierbrk reviewed
Por favor tratar de no dejar cambios innecesarios, tratar de reparar el formato de todos los archivos. 
tratar de explicar porque quitar la restricción de máxima temperatura ? y demás cambios no asociados a esta pull request. 

MUY IMPORTANTE !!! 
AGREGAR UNA PRUEBA UNITARIA CON LA CANTIDAD DE CARACTERES NUEVA ! ! ! ! !

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/configurator.lua
> +return configurator
y este ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if new_max_temp ~= nil and new_max_temp >= 0
este cambio sigue quedando ? de no limitar la temperatura máxima a 60 ? por que solo a mas de 0 ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if type(new_tray_date) == "number" and #tostring(new_tray_date) < 30 then
y esto porque lo cambiaste ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if type(new_incubation_period) == "number" and #tostring(new_incubation_period) < 20 then
y esto porque lo cambiaste ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if type(new_hash) == "string" and #new_hash < 30 then
este cambio y el del nombre son los que deben quedar

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +if type(new_incubator_name) == "string" and #new_incubator_name < 30 then
este cambio y el del hash son los que deben quedar

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/http_request_methods.lua
> +return http_request_methods
porque ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/tables.lua
> +	min_hum = 60
porque ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/tables.lua
> +	config_to_test_str = {}
porque ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/tables.lua
> -	tray_two_date = 1234567892,
porque ?

2024-11-27 14:34 UTC, javierbrk commented on src/embedded/test/tdd_api_rest/tables.lua
> +return tables
porque ?

2024-12-02 23:12 UTC, closed without merging