Add WiFi Manager for new connections.
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #31
Opened 2024-04-26 03:03 UTC by JereC4str0

#30

2024-04-26 11:59 UTC, javierbrk commented
¿ Este pull esta fucionando ? ¿ podrias agregar una descripción ?  
si este no es el que comentaste que funcionaba, podes hacer otro pull con el que si funciona ?

2024-04-26 22:04 UTC, javierbrk requested changes

2024-05-01 19:08 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
> +	if new_config_table.ssid ~= W.station_cfg.ssid then
es cierto, lo habiamos hablado en la reunion de soft anterior, mil disculpas, ya hice el cambio

2024-05-01 19:08 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
>  configwifi()
le cambie el nombre a init_wifi, en mi opinion es mas intuitivo, pero puedo dejar el que tenia de ser necesario

2024-05-01 19:09 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
> +W.station_cfg.ssid = SSID
logrado

2024-05-08 21:11 UTC, javierbrk commented
que pasa cuando se reinicia el esp ? desde y cuando se guardan las configuraciones ? y el wifi ?

2024-06-27 13:59 UTC, javierbrk commented
@JereC4str0 podes subir los nuevos binarios ? ni bien este avisale a santi para que pruebe este pull

2024-07-10 18:55 UTC, Santiagocetran commented on src/embedded/app/wifiinit.lua
> +	new_config_table.passwd ~= new_config_table.passwd then
```lua
new_config_table.passwd ~= new_config_table.passwd
```

Esta condición va a ser siempre falso

2024-07-10 18:55 UTC, Santiagocetran reviewed
Lo probamos con el nuevo firmware y no funcionó :(

2024-07-10 23:21 UTC, JereC4str0 commented
> @JereC4str0 podes subir los nuevos binarios ? ni bien este avisale a santi para que pruebe este pull

listo :)
#62

2024-08-19 18:00 UTC, merged

2024-08-30 14:40 UTC, javierbrk commented
curl -X POST http://192.168.16.10/config -H "Content-Type: application/json" -d '{"rotation_duration":5000,"rotation_period":360000,"min_temperature":37.3,"max_temperature":37.8,"ssid":"OpenWrt","passwd":""}'