Add Advances in Humidifier controller
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #61
Opened 2024-07-08 23:12 UTC by JereC4str0

2024-07-10 16:39 UTC, javierbrk requested changes
Teniendo en cuenta que la funcion de control se llama cada 3s. Viendo lo que pilusiste creo que se podría acomodar así. Una variable que habilita o deshabilita el humidificador. 

Si hum < 60 
  Si humid habilitado
    Si hum apagado 
      Encender hum
      Encender timer para deshabilitar el hum en 15 min
   Else
      Hum ya está prendido 
  Else
Hum deshabilitado ... Esperrar
Apagar hum
End

If hum > 60 
Apagar hum 
Desactivar timer
End

Timer a los 15 min: deshabilitar humid y apagar. Activar otro timer para volver a habilitar humid en otros 15 min.

2024-07-10 16:39 UTC, javierbrk commented on src/embedded/app/incubatorController.lua
> +    cal_init_time = epoch2cal(init_time)
cada vez que se llama debe calcular fechas y horas ... mejor usar timer

2024-07-10 16:39 UTC, javierbrk commented on src/embedded/app/incubatorController.lua
> +    elseif hum >= hum_max and is_twenty then
incubator.is_twenty e is_twenty  son dos variables diferentes

2024-07-10 23:31 UTC, JereC4str0 commented on src/embedded/app/incubatorController.lua
> +    elseif hum >= hum_max and is_twenty then
me comí el incubator. de la 113

2024-07-12 09:20 UTC, JereC4str0 commented
vscodium me formateó el documento.

hice los cambios a la funcion siguiendo el pseudocodigo:

[los cambios empiezan desde aca](https://github.com/AlterMundi-MonitoreoyControl/Proyecto-Incubadora/blob/a82bae3f4297364260e9cb52ac3bf822bd543a2a/src/embedded/app/incubatorController.lua#L86)

2024-07-16 13:37 UTC, javierbrk commented
lo pudiste probar ?

2024-07-16 23:01 UTC, JereC4str0 commented
use tabs con 2 espacios como acordamos :)

2024-08-05 12:12 UTC, javierbrk commented
Esta rama quedo obsoleta fue una pena porque estaba casi lista. Si logramos coordinar horarios y jornadas de trabajo podemos hacer mas efectivo el proyecto y avanzar juntos !

2024-08-05 12:12 UTC, closed without merging