Fix API and some minor bugs
AlterMundi-MonitoreoyControl/Proyecto-Incubadora pull request #85
Opened 2024-09-05 22:40 UTC by JereC4str0

# Cambios Solicitados

## Nuevos campos agregados:

* ```tray_one_date```
* ```tray_two_date```
* ```tray_three_date```
* ```incubator_period```
* ```hash```
* ```incubator_name```
* ```hum_max```
* ```hum_min```	

### Cambios menores 
- Cambié la forma en la que se escribe el archivo JSON de configuracion por defecto por una sintaxis que permite los saltos de linea y es mucho mas legible

- Se eliminó el ssid y passwd de IncubatorController, ahora esto lo maneja el modulo ```wifiinit.lua```

- inicialicé los valores de la bandejas en 0

- Agregué la logica que manejan los datos de estos campos

- Agrego pruebas unitarias 

- Añadí el modulo logs en wifiinit

## Pasos para probar esta Pull Request: 
 1. Cargar los archivos modificados en esta pull request al ESP32
 2. Iniciar la API 
 3. Realizar una solicitud POST a la IP asignada 
 4. Comprobar que se estén realizando los cambios en la tabla incubator		 

### Este fue el json que utilicé para hacer las pruebas manuales:

```json
{
	"rotation_duration":5000,
	"rotation_period":3600000,
	"min_temperature":37.3,
	"max_temperature":37.8,
	"tray_one_date":1234567890,
	"tray_two_date":1234567890,
	"tray_three_date":1234567890,
	"incubation_period":1234567890,
	"hash":"1234567890",
	"incubator_name":"incubator_1",
	"max_hum": 70,
	"min_hum": 60
}
```

#### Utilice una extencion de vscodium para hacer las peticiones Web

Este es el [Link](https://www.thunderclient.com/) de la extencíon 

#### Primero verifico que el archivo ```config.json```se esté creando correctamente
para eso  se puede eliminar el archivo config.json de forma manual usando la siguiente linea:

```lua
file.remove("config.json") 
```

despues de esto se debe reiniciar el ESP32 para que cree un archivo nuevo por defecto

deberia ver algo como esto: 

```sh
[TRACE 1970-01-01 00:00:05 DST:0]  : Creating a new config file 
```

#### Recorrer la tabla incubator para ver si los valores cambiaron:
```lua 
for k,v in pairs(incubator) do print (k,v) end 
```
 con esta linea se puede ver el contenido total de la tabla incubator con todas sus funciones y valores

esta es la salida antes de realizar la peticion POST

```lua
rotation_duration	5000
tray_one_date	0
max_hum	70
hash	1234567890
hum_turn_on_time	0
humidifier_off_time	15
incubator_name	incubator_1
rotation_period	3600000
humidity	99.9
hum_turn_off_time	0
max_temp	37.8
min_hum	60
pressure	99.9
min_temp	37.3
tray_two_date	0
tray_three_date	0
incubation_period	0

```
esta es la salida despues de realizar la peticion POST:
```lua
rotation_duration	5000
tray_one_date	1234567890
max_hum	70
hash	1234567890
incubator_name	incubator_1
rotation_period	3600000
max_temp	37.8
min_hum	60
pressure	99.9
min_temp	37.3
tray_two_date	1234567890
tray_three_date	1234567890
incubation_period	1234567890
```

##### nos podemos dar una idea si los valores cambiaron mirando el JSON que enviamos con los valores reflejados en la tabla

si la peticion fué exitosa deberia ver algo como esto:
[![imagen.png](https://i.postimg.cc/kM8rb1zt/imagen.png)](https://postimg.cc/z3JPmjJJ)

otra forma de ver si se reflejaron los cambios es hacer una peticíon GET desde thunder client (extencion de vscodium) o desde el mismo navegador

[![imagen.png](https://i.postimg.cc/5NnsY84C/imagen.png)](https://postimg.cc/1fVGbnNm)

2024-09-05 22:48 UTC, JereC4str0 commented
Mañana voy a actualizar las pruebas TDD para los nuevos campoos

2024-09-09 13:26 UTC, JereC4str0 commented
sacar validacion de config_file

2024-09-09 13:59 UTC, javierbrk requested changes

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/configurator.lua
> +	local new_file = io.open("config.json", "w")
quitar esta verificación

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/configurator.lua
> +		elseif param == "max_hum" then
arreglar indentación

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +function M.set_tray_three_date(new_tray_three_date)
esta función se repite tres veces, podes ponerle como parametro el tray y asi solo se escribe una vez

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +			and new_max_hum >= M.min_hum
deberia ser mayor a la minima

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +		and new_min_hum <= M.max_hum
me parece que deberia ser menor, no igual

2024-09-09 13:59 UTC, javierbrk commented on src/embedded/app/wifiinit.lua
> -		wifi.sta.disconnect()
porque comentaste esto ?

2024-09-11 00:44 UTC, JereC4str0 commented on src/embedded/app/configurator.lua
> +		elseif param == "max_hum" then
[![imagen.png](https://i.postimg.cc/90rx969s/imagen.png)](https://postimg.cc/JHCcVdPQ)

creo que es algo del formateo de github, en mi vscode se ve bien adjunto las configuraciones del mismo :
```json
{
    "workbench.colorTheme": "Tokyo Night Dark Enhanced",
    "editor.fontFamily": "Fira Code ",
    "editor.fontLigatures": true,
    "editor.detectIndentation": false,
    "editor.tabSize": 2,
		"editor.insertSpaces": false,
}
```

2024-09-11 00:48 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
> -		wifi.sta.disconnect()
porque cada vez que se envia una peticion POST desde busted para probar las configuraciones intenta conectarse a otro wifii, esto termina con un burnout del ESP y no me deja seguir corriendo pruebas

2024-09-11 01:37 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
> -		wifi.sta.disconnect()
ya esta descomentado

2024-09-11 01:42 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
> -		wifi.sta.disconnect()
ahora esta descomentado

2024-09-11 10:24 UTC, javierbrk commented
Solo faltarían pruebas unitarias.

2024-10-18 20:39 UTC, javierbrk requested changes
falta arreglar el código, correr las pruebas y si pasa deberiamos intentar correr en otra incubadora

2024-10-18 20:39 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	incubator_name = "incubator_1"
falta una coma
sugiero que corras siempre las pruebas antes de hacer commit

2024-10-18 20:39 UTC, javierbrk commented on src/embedded/app/incubator.lua
> +	if type(new_incubation_period) == "number" and #tostring(new_incubation_period) == 10 then
siempre va a tener 10 dígitos ?

2024-10-18 20:39 UTC, javierbrk commented on src/embedded/app/wifiinit.lua
>  		wifi.sta.disconnect()
como esta ahora si no cambio nada, es decir  config_changed es falso, desconectas el ap ? porque es necesario hacer eso ? cada vez que cambies un parametro te va a desconectar del wifi ? cambias la fecha de la bandeja y te desconecta ?

2024-10-22 20:18 UTC, JereC4str0 commented on src/embedded/app/incubator.lua
> +	if type(new_incubation_period) == "number" and #tostring(new_incubation_period) == 10 then
hasta el año 2286

2024-10-22 20:18 UTC, JereC4str0 commented on src/embedded/app/incubator.lua
> +	if type(new_incubation_period) == "number" and #tostring(new_incubation_period) == 10 then
estabamos usando Unix epoch time

2024-10-22 20:20 UTC, JereC4str0 commented on src/embedded/app/wifiinit.lua
>  		wifi.sta.disconnect()
solo hace el cambio si el ssid y passwd cambiaron, no con todos, propongo hacer otra pull request para esto, para no mezclar las cosas :)

2024-11-01 15:52 UTC, merged